# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GfXawexZ8FAZOxv2g3WlumHL3wl0CPyI
"""


!pip install -q tensorflow scikit-learn joblib

import numpy as np
import pandas as pd
import os
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from sklearn.preprocessing import MinMaxScaler
import joblib

from google.colab import files
import glob


os.makedirs("models_lstm", exist_ok=True)


def train_lstm_for_product(file_path, save_dir="models_lstm", sequence_length=10):
    df = pd.read_csv(file_path)
    product_id = os.path.basename(file_path).split('.')[0]

    if len(df) <= sequence_length:
        print(f"❌ Skipping {product_id} — not enough data.")
        return

    prices = df['price'].values.reshape(-1, 1)
    scaler = MinMaxScaler()
    scaled_prices = scaler.fit_transform(prices)

    X, y = [], []
    for i in range(sequence_length, len(scaled_prices)):
        X.append(scaled_prices[i-sequence_length:i])
        y.append(scaled_prices[i])
    X, y = np.array(X), np.array(y)

    model = Sequential()
    model.add(LSTM(50, activation='relu', input_shape=(X.shape[1], 1)))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mse')
    model.fit(X, y, epochs=30, verbose=0)

   
    model.save(f"{save_dir}/{product_id}_lstm.h5")
    joblib.dump(scaler, f"{save_dir}/{product_id}_scaler.save")

    print(f"✅ Trained and saved: {product_id}")

csv_files = glob.glob("*.csv")
for file in csv_files:
    train_lstm_for_product(file)

import shutil
shutil.make_archive("models_lstm", 'zip', "models_lstm")
files.download("models_lstm.zip")

from tensorflow.keras.models import load_model

model = load_model(f"models_lstm/product_101_lstm.h5", compile=False)

import joblib
import numpy as np

# Load scaler
scaler = joblib.load(f"models_lstm/product_101_scaler.save")

# Use any 10 recent prices
test_prices = np.array([500, 505, 510, 495, 490, 500, 515, 520, 525, 530]).reshape(-1, 1)

# Normalize
scaled_input = scaler.transform(test_prices)
X = np.array([scaled_input])  # Shape: (1, 10, 1)

# Predict
predicted_scaled = model.predict(X)
predicted_price = scaler.inverse_transform(predicted_scaled)[0][0]

print(f"📈 Predicted next price: ₹{predicted_price:.2f}")